''' <summary>
''' Not all constants :)
''' </summary>
Public Class Constants
    ''' <summary>
    ''' Startup ASCII art.
    ''' </summary>
    Public Const ASCIIART As String = "                                            
____________       __________               
____  _/_  /______ ___  /__(_)_____ _______ 
 __  / _  __/  __ `/_  /__  /_  __ `/_  __ \
__/ /  / /_ / /_/ /_  / _  / / /_/ /_  / / /
/___/  \__/ \__,_/ /_/  /_/  \__,_/ /_/ /_/ 
                                            
_________                                   
__  ____/_____ ___________________________  
_  /    _  __ `/_  __ \_  __ \  __ \_  __ \ 
/ /___  / /_/ /_  / / /  / / / /_/ /  / / / 
\____/  \__,_/ /_/ /_//_/ /_/\____//_/ /_/  
(ASCII Art Generated by patorjk.com)
                                            
"
    ''' <summary>
    ''' Application version
    ''' </summary>
    Public Const AppVer As String = "1.0.0-bt-b1"
    ''' <summary>
    ''' Appliation configuration file's name.
    ''' </summary>
    ''' <returns></returns>
    Public Shared ReadOnly Property ConfFile As String = IO.Path.Combine((New IO.FileInfo(Reflection.Assembly.GetExecutingAssembly.Location)).DirectoryName, "ItalianCannon.json")
    ''' <summary>
    ''' Current configuration.
    ''' </summary>
    ''' <returns></returns>
    Public Shared Property CurrentConfigurations As Configurations.ConfObj

    Public Shared Property ThrId As Integer = 0

    Public Shared Property Total As UInt64 = 0

    Public Shared Property SW As New Stopwatch
End Class
